
package game.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GamesService", targetNamespace = "http://ws.soap.game/", wsdlLocation = "https://games-sde.herokuapp.com/games?wsdl")
public class GamesService
    extends Service
{

    private final static URL GAMESSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMESSERVICE_EXCEPTION;
    private final static QName GAMESSERVICE_QNAME = new QName("http://ws.soap.game/", "GamesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://games-sde.herokuapp.com/games?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMESSERVICE_WSDL_LOCATION = url;
        GAMESSERVICE_EXCEPTION = e;
    }

    public GamesService() {
        super(__getWsdlLocation(), GAMESSERVICE_QNAME);
    }

    public GamesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMESSERVICE_QNAME, features);
    }

    public GamesService(URL wsdlLocation) {
        super(wsdlLocation, GAMESSERVICE_QNAME);
    }

    public GamesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMESSERVICE_QNAME, features);
    }

    public GamesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GamesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Games
     */
    @WebEndpoint(name = "GamesImplPort")
    public Games getGamesImplPort() {
        return super.getPort(new QName("http://ws.soap.game/", "GamesImplPort"), Games.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Games
     */
    @WebEndpoint(name = "GamesImplPort")
    public Games getGamesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.game/", "GamesImplPort"), Games.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMESSERVICE_EXCEPTION!= null) {
            throw GAMESSERVICE_EXCEPTION;
        }
        return GAMESSERVICE_WSDL_LOCATION;
    }

}
