
package game.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Games", targetNamespace = "http://ws.soap.game/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Games {


    /**
     * 
     * @param appId
     * @param name
     * @return
     *     returns game.soap.ws.Game
     */
    @WebMethod
    @WebResult(name = "game", targetNamespace = "")
    @RequestWrapper(localName = "getGame", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.GetGame")
    @ResponseWrapper(localName = "getGameResponse", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.GetGameResponse")
    @Action(input = "http://ws.soap.game/Games/getGameRequest", output = "http://ws.soap.game/Games/getGameResponse")
    public Game getGame(
        @WebParam(name = "appId", targetNamespace = "")
        long appId,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<game.soap.ws.Game>
     */
    @WebMethod
    @WebResult(name = "games", targetNamespace = "")
    @RequestWrapper(localName = "getGameList", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.GetGameList")
    @ResponseWrapper(localName = "getGameListResponse", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.GetGameListResponse")
    @Action(input = "http://ws.soap.game/Games/getGameListRequest", output = "http://ws.soap.game/Games/getGameListResponse")
    public List<Game> getGameList();

    /**
     * 
     * @return
     *     returns java.util.List<game.soap.ws.Game>
     */
    @WebMethod
    @WebResult(name = "games", targetNamespace = "")
    @RequestWrapper(localName = "init", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://ws.soap.game/", className = "game.soap.ws.InitResponse")
    @Action(input = "http://ws.soap.game/Games/initRequest", output = "http://ws.soap.game/Games/initResponse")
    public List<Game> init();

}
